[package]
name = "babylon_canvas_wgpu_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
femtovg = { workspace = true }
image = { workspace = true }
imgref = { workspace = true }
pollster = { workspace = true }
rgb = { workspace = true }
wgpu = { workspace = true }
