[package]
name = "babylon_graphics_backend"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["staticlib"]

[features]
default = []
upstream_wgpu_native = ["babylon_wgpu_native_shim/upstream_wgpu_native"]

[dependencies]
babylon_wgpu_native_shim = { path = "upstream-shim" }
pollster = { workspace = true }
raw-window-handle = { workspace = true }
wgpu = { workspace = true }
